/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rachel
 */
public class pant3 extends javax.swing.JFrame {

    /**
     * Creates new form pant3
     */
    public pant3() {
        initComponents();
        model=(DefaultTableModel) jTable2.getModel(); 
    }
    public ArrayList<clase1> arr;
  
    DefaultTableModel model; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(153, 153, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipo", "Volante", "Referí", "Set", "Jornada", "Mosca"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Ordenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton1)
                        .addGap(67, 67, 67)
                        .addComponent(jButton3)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    void ordenar_datos(){
        clase1 temp=new clase1();
        for(int i=0;i<arr.size();i++){
            for(int x=1;x<arr.size()-1;x++){
                if(arr.get(x-1).getSet()<arr.get(x).getSet()){
                    temp.setEquipo(arr.get(x-1).getEquipo());
                    temp.setVolante(arr.get(x-1).getVolante());
                    temp.setReferi(arr.get(x-1).getReferi());
                    temp.setSet(arr.get(x-1).getSet());
                    temp.setJornada(arr.get(x-1).getJornada());
                    temp.setMosca(arr.get(x-1).isMosca());
                    
                    arr.get(x-1).setEquipo(arr.get(x).getEquipo());
                    arr.get(x-1).setVolante(arr.get(x).getVolante());
                    arr.get(x-1).setReferi(arr.get(x).getReferi());
                    arr.get(x-1).setSet(arr.get(x).getSet());
                    arr.get(x-1).setJornada(arr.get(x).getJornada());
                    arr.get(x-1).setMosca(arr.get(x).isMosca());
                    
                    arr.get(x).setEquipo(temp.getEquipo());
                    arr.get(x).setVolante(temp.getVolante());
                    arr.get(x).setReferi(temp.getReferi());
                    arr.get(x).setSet(temp.getSet());
                    arr.get(x).setJornada(temp.getJornada());
                    arr.get(x).setMosca(temp.isMosca());                                                                
                }             
            }
        }
      }
    
    
    
    void presentar(){
       model.setNumRows(0);
      
        for(int i=0;i<3;i++){
                model.addRow(new Object[]{
                    arr.get(i).getEquipo(),
                    arr.get(i).getVolante(),
                    arr.get(i).getReferi(),
                    arr.get(i).getSet(),
                    arr.get(i).getJornada(),
                    arr.get(i).isMosca()                
                });
        }
     }
    
      void present_datos(){
     for(int i=0; i<arr.size(); i++){
         model.addRow(new Object[]{arr.get(i).getEquipo(), arr.get(i).getVolante(), arr.get(i).getReferi(),
                                   arr.get(i).getSet(), arr.get(i).getJornada(), arr.get(i).isMosca()}); 
     }
     }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       present_datos(); 
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ordenar_datos(); 
       presentar(); 
    }//GEN-LAST:event_jButton1ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pant3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pant3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pant3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pant3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pant3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
